### ISSUE TITLE
Merge Ingredient when occurred in multiple steps

### ISSUE THREAD

**Issue by luksal** [TandoorRecipes/recipes#196] opened 2020-09-30 12:07 UTC
When an ingredient is used in multiple steps, the recipe should sum them up.

**Comment by vabene1111** [comment] 2020-09-30 15:56
hmm thats an interesting tought. I definitely dont want this to happen as it is very important for me to know how much of what is used in which step (for example when baking bread, i will need flour for basically every step but different amounts).

If this feature were to be added it would definitely need to be a user setting.

**Comment by luksal** [comment] 2020-10-03 11:52
I don't know what's the best way to do it, right know I'm writing my recipes like this (sorry for the german text):
<img width="972" alt="Bildschirmfoto 2020-10-03 um 13 49 20" src="https://user-images.githubusercontent.com/9074730/94990869-63e6fd00-057f-11eb-8a6a-f1170ad39087.png">
which results in an Ingredient List like this:
<img width="424" alt="Bildschirmfoto 2020-10-03 um 13 48 52" src="https://user-images.githubusercontent.com/9074730/94990880-72cdaf80-057f-11eb-87b9-d03caa9340eb.png">
I really like, that you can see the ingredients for the single steps, but for checking your own stock, it would be nice to switch the increment list (temporary) to a summed view.

**Comment by vabene1111** [comment] 2020-10-04 18:38
i understand what you mean. I guess it would be a per recipe setting if the ingredients should be merged in the top most ingredient view.

To be honest the view page is a bit of a mess and needs to be rewritten in some parts so its probably something that can be done in one go at some point.

**Comment by tdvantine** [comment] 2021-02-16 02:29
I would have to agree here, just the other day I was adding in some ingredients and added different amounts in two steps, but it duplicated the ingredient in the main ingredients list and i found that annoying. My workaround was to add the full amount in one step, then bold the amounts in others, cause MD is useful.

**Comment by vabene1111** [comment] 2021-02-16 08:31
In the new release you can even use templating to write the ingredients directly into the text (although i don't think partial amounts are possibel, that would definitely be interesting)

i have some high priority features that are first in line but this is definitely something that needs to be looked at, i totally understand your point and it definitely makes sense to aggregate the ingredients for many recipes, at the same time for some it doesn't so both ways need to be supported.

**Comment by DaFlowah** [comment] 2021-02-20 17:37
I just logged a duplicate of this feature request (which I just closed). I'd like to see the same thing, putting the same ingredients all together in the main ingredient list if these ingredients are showing multiple times in different steps.
But I guess this might become complicated for (sub)multiples, for example if I have _300 g of flour_ in Step 1 and _1 kg of flour_ in Step 2.

**Comment by vabene1111** [comment] 2021-02-20 19:59
yes, the last note definitly wont work with the current setup but i plan on adding unit conversions for the shopping list anyway so might as well add it there too

**Comment by smilerz** [comment] 2022-01-25 16:08
duplicate #1325

**Closed by smilerz** 2022-01-25 16:08 UTC
Labels: enhancement
