### ISSUE TITLE
Empty unit name when importing

### ISSUE THREAD

**Issue by Battleman** [TandoorRecipes/recipes#2690] opened 2023-10-21 10:47 UTC
### Tandoor Version

1.5.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When importing a recipe from a website, and moving fields around, _sometimes_ a non-existing unit is replaced by an empty unit. 

<details>
<summary>Extract from the JSON generated</summary>

```json
        {
            "instruction": "Couper l'avocat et le piment en deux, les nettoyer et les émincer. Hacher finement l'oignon rouge.  ",
            "ingredients": [
                {
                    "amount": 0,
                    "food": {
                        "name": "avokado"
                    },
                    "unit": null,
                    "note": "",
                    "original_text": "avokado"
                },
                {
                    "amount": 0,
                    "food": {
                        "name": "grønn chili"
                    },
                    "unit": {
                        "name": ""
                    },
                    "note": "",
                    "original_text": "grønn chili"
                },
                {
                    "amount": 0,
                    "food": {
                        "name": "rødløk"
                    },
                    "unit": {
                        "name": ""
                    },
                    "note": "",
                    "original_text": "rødløk"
                }
            ],
            "show_ingredients_table": true
        },
```

</details>

This particular extract comes from [this website](https://meny.no/oppskrifter/vegetar/krydret-gresskargryte/), but simply importing the link works immediately. I believe the problem happens when moving ingredients around, before importing.

The API response is a simple 400, indicating that "This field may not be blank" (at the correct place). I've tried entering the ingredient and modifying it, but it doesn't seem possible to simply "delete". I haven't tried manually setting a random unit.

Unfortunately, it's not super easy to reproduce, with clear steps.  Happens "sometimes".
Current workaround is to use the browser's console network tab, figure out which ingredient is broken, and delete it altogether from the import. Maybe also simply set a random unit, and delete it afterwards.

**Possible solutions:** 
* When the unit just contains an empty name, consider it a null unit
* Prevent the empty unit from appearing in the first place.

**Comment by Yubraj977** [comment] 2023-10-27 03:31
#2690 HI BRO JUST NAVIGATING WHILE LEARNING DONT TAKE IT SEROUS

**Comment by vabene1111** [comment] 2023-11-27 21:25
ok so this is actually kind of the expected/intended behavior, the system just does not expect you to open the editor and not enter anything 

```javascript
prepareIngredientEditModal: function (step, ingredient) {
            if (ingredient.unit === null) {
                ingredient.unit = {
                    "name": ""
                }
            }
            if (ingredient.food === null) {
                ingredient.food = {
                    "name": ""
                }
            }
            this.current_edit_ingredient = ingredient
            this.current_edit_step = step
        },
```

but that of course makes sense, you should be able to just leave the unit empty, i fill fix it

**Comment by vabene1111** [comment] 2023-11-27 21:34
ok so there was actually already a method handling this case but it only triggered when using one of the buttons not the close or clicking in the background. Its now fixed

**Closed by vabene1111** 2023-11-27 21:34 UTC
