### ISSUE TITLE
settings dont save sharing prefs

### ISSUE THREAD

**Issue by benneti** [TandoorRecipes/recipes#2115] opened 2022-10-11 06:38 UTC
### Issue

Adding another user to a shopping list or mealplan does not work.

Additional notes: one of the users was created by allauth (and then manually added to the users group and space).

Not sure whether this is a setup issue or a bug so I tagged as setup issue for now.

### Tandoor Version

1.4.4

### OS Version

Nixos unstable

### Setup

Others (please state below)

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Other

nixos module with custom settings

### Environment file

```shell
ALLOWED_HOSTS="mydomain.com";
        DB_ENGINE = "django.db.backends.postgresql";
        MEDIA_ROOT = "/var/lib/tandoor_recipes/media";
        POSTGRES_HOST = "/run/postgresql";
        POSTGRES_USER = "tandoor_recipes";
        POSTGRES_DB = "tandoor_recipes";
        GUNICORN_CMD_ARGS = "--bind=unix:/run/tandoor-recipes/tandoor-recipes.sock";
        ENABLE_SIGNUP=0;
        MEDIA_URL = "/media/";
        GUNICORN_MEDIA = 0;
```

### Relevant logs

```shell
Oct 11 08:35:31 prodigy systemd[1]: Starting Tandoor Recipes server...
Oct 11 08:35:34 prodigy tandoor-recipes-pre-start[543257]: Operations to perform:
Oct 11 08:35:34 prodigy tandoor-recipes-pre-start[543257]:   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, s>
Oct 11 08:35:34 prodigy tandoor-recipes-pre-start[543257]: Running migrations:
Oct 11 08:35:34 prodigy tandoor-recipes-pre-start[543257]:   No migrations to apply.
Oct 11 08:35:35 prodigy systemd[1]: Started Tandoor Recipes server.
Oct 11 08:35:35 prodigy gunicorn[543261]: [2022-10-11 08:35:35 +0200] [543261] [INFO] Starting gunicorn 20.1.0
Oct 11 08:35:35 prodigy gunicorn[543261]: [2022-10-11 08:35:35 +0200] [543261] [INFO] Listening at: unix:/run/tandor-recipes/tandor-recipes.sock (543261)
Oct 11 08:35:35 prodigy gunicorn[543261]: [2022-10-11 08:35:35 +0200] [543261] [INFO] Using worker: sync
Oct 11 08:35:35 prodigy gunicorn[543287]: [2022-10-11 08:35:35 +0200] [543287] [INFO] Booting worker with pid: 543287
```

**Comment by vabene1111** [comment] 2022-10-11 11:10
have you tried with a just "normally" created user that joined the space by invitation linkt the way its supposed to be ?

When does "doesn't work" mean, you cant select the sharing person or the shared person does not see what you shared with them.

**Comment by benneti** [comment] 2022-10-11 11:24
yes I did and the same happend.
The same or "doesn't work" means, that I can add another user to "Share Shopping List" and it shows the green success box on the bottom right, the other user does however not see my shopping list, and when I refresh my tab and go into settings the option "Share Shopping List" is empty (the same is true for the default meal plan sharing setting, single meals however work). I hope this describes it a bit better.

**Comment by devmato** [comment] 2022-10-11 21:13
I have the some problem on the latest docker image. 
Cannot add another user to my sharing list. Even when i try to call the API-Endpoint "retrieveUserPreference" manually like stated in the API docs the setting is just ignored and i get back an empty list for the shopping_share property so it seems like a problem on the backend. Same problem on meal plan sharing (haven't tried calling the API manually though)

**Comment by vabene1111** [comment] 2022-10-13 12:07
ok so i guess the issue is related to a bug on the sharing page (which I recently reworked so likely something broke there). Thanks for the feedback, i know where to look now, hope to get to fixing this soon.

**Comment by benneti** [comment] 2022-10-13 12:11
thanks, if I can provide any more information please let me know!

**Comment by cryptoluks** [comment] 2022-10-18 09:25
New Tandoor user here. First of all: Thanks for this great tool!

Stumbled across this bug by myself, using Tandoor 1.4.4 with Authelia Reverse Proxy Auth and a Traefik docker-compose setup.

The PATCH to `/api/user-preference/1/` returns 200, but nothing is persisted. Nothing relevant seems to be logged too.

**Comment by vabene1111** [comment] 2022-10-31 18:43
fixed in next release, forgot to actually store the component value upon change 🙈 thanks for the input provided by everyone.

**Closed by vabene1111** 2022-10-31 18:43 UTC
Labels: bug
