### ISSUE TITLE
Bad request when saving imported recipie 

### ISSUE THREAD

**Issue by alpar-t** [TandoorRecipes/recipes#2257] opened 2023-01-04 18:34 UTC
### Tandoor Version

latest docker image

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Other

Also tried with Nginx

### Bug description

When trying to import https://thegreatbritishbakeoff.co.uk/recipes/all/paul-hollywood-dampfnudel/  I get an error 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/2565652/210625215-3ee7b07d-0793-415a-8a82-237b28add911.png">

### Relevant logs

```shell
Bad Request: /api/recipe/
Bad Request: /api/recipe/
```

Not sure how to get more information in the logs but happy to provide it
```

**Comment by vabene1111** [comment] 2023-01-04 21:29
i can reproduce this issue and immediatly see some very strange behavior in the ingredient list, probably just some strange data structure on the posted site, will look into this.

**Comment by Battleman** [comment] 2023-01-14 12:31
I've seen the same issue on [another recipe](https://qblog.qoqa.ch/fr/posts/4121). The problem is that some whitespaces are detected as ingredients, which cause a problem when importing.

**Comment by vabene1111** [comment] 2023-01-14 15:24
Yes that's possible. Shouldn't be hard to fix but had some other stuff to work on and not yet time to get to this.

**Comment by Battleman** [comment] 2023-01-14 15:32
I see multiple fixes, with different levels of QOL and difficulty:
* Automatically trim whitespaces and skip empty ingredients
* Allow to delete an ingredient before importing
* Allow to _edit_ an ingredient before importing

This loosely relates to #177 and would also be fixed by #1885

**Comment by vabene1111** [comment] 2023-01-16 19:42
fixed loading of empty ingredients. also have one other idea i want to check to improve editability, need to see if it works.

**Closed by vabene1111** 2023-01-16 19:42 UTC
Labels: bug
