### ISSUE TITLE
Shopping list problem when an ingredient is used in more than one recipe

### ISSUE THREAD

**Issue by 0utl4w** [TandoorRecipes/recipes#965] opened 2021-10-19 13:45 UTC
### Version
v0.17.2

### Bug description
When an item on the shopping list is the result of an igredient that is used in more than one recipe the values of the units are not added, they a displayed next to each other.

At first I thought there is a problem with the decimal seperators because I had numbers with more than one point. But those seperators didn't make sense at all. So I figured out that the first number was the value of the first recipe and the value from the second recipe is simply added right behind.,, I think a screenshot explains it better
![2021-10-19 15_37_39-Einkaufsliste - Brave](https://user-images.githubusercontent.com/80005700/137922543-f0964ffd-52b6-4343-91e1-c7df446d2b67.png)

In my example it should be 6 Knoblauchzehen (it displays 2.004.00) and so on.

**Comment by vabene1111** [comment] 2021-10-19 14:30
i added some decimal rounding in the last release, i fear this might be the cause of this issue. I think i will fix it for the old version as well so that smilerz isnt to pressured to get the new one out .. or maybe i should leave it broken 🤔 😂

**Comment by vabene1111** [comment] 2021-10-19 15:02
fixed in next release

**Closed as completed by vabene1111** 2021-10-19 15:02 UTC
Labels: bug
