### ISSUE TITLE
Include recipes of sub-keywords in search

### ISSUE THREAD

**Issue by jpbaril** [TandoorRecipes/recipes#1022] opened 2021-11-05 03:40 UTC
**Is your feature request related to a problem? Please describe.**
Keywords can be moved under other keywords to create a hierarchy of keywords/categories.
Yet when searching for recipes if I select a top level keyword then the search does not show the recipes that have been categorized with a sub-level keyword of that top level.

**Describe the solution you'd like**
Selecting a top level keyword should show recipes tagged with that keyword but also with those under it.
Eg. I created that hierarchy:
- Meat
-- Beef
-- Pork
-- Poultry
--- Chicken
--- Duck

Selecting keyword 'Meat' in search should show me all recipes tagged with either: Beef, Pork, Poultry, Chicken, Duck.

**Comment by smilerz** [comment] 2021-11-05 03:51
@jpbaril if you change the and/or selector to “and” you should  get the behavior you expect.

**Comment by jpbaril** [comment] 2021-11-05 04:20
> @jpbaril if you change the and/or selector to “and” you should get the behavior you expect.

Not really.
I did a test. I checked 'Pork' and 'Poultry'.
The result was that it either only shown my recipes of 'Pork' or shown nothing. Never my Chicken repices were included in the results.

**Comment by smilerz** [comment] 2021-11-05 12:49
This works for me - 
![image](https://user-images.githubusercontent.com/1808639/140511673-69fe5648-be62-4253-a2f1-d7c396133656.png)
![image](https://user-images.githubusercontent.com/1808639/140511745-d5f4557b-a982-4658-8767-3d0eab965388.png)

Can you please confirm that the Chicken keyword (case sensitive) is applied to a recipe and that there are no duplicate keywords.
If that is still true can you enable debug mode and provide the URL of the search (will be in the format of /recipes/api/recipe/?query=&......)

**Comment by jpbaril** [comment] 2021-11-07 17:28
Here are the answers in screenshots.
P.S. Boeuf=Beef, Porc=Pork, Volaille=Poultry,Poulet=Chicken,Canard=Duck
![Trying to filter Pork and Poultry](https://user-images.githubusercontent.com/5779633/140655178-8b853a40-d94f-470a-8f41-e12fa6cc85dc.png)
![All the recipes](https://user-images.githubusercontent.com/5779633/140655177-90b8156f-f90f-457c-a9c3-caaf6054c570.png)

**Comment by smilerz** [comment] 2021-11-07 17:48
Right now having the toggle on "OR" only does search on the selected keyword or food - ignoring children.   
When it is toggled to "AND" mode it will search for the keyword and all of its children.   This is the intended behavior.

![image](https://user-images.githubusercontent.com/1808639/140655912-85c45c0e-81a5-4843-baf7-22db5c0aa64d.png)
 
In a future release this behavior may become configurable.

**Comment by jpbaril** [comment] 2021-11-07 18:47
Oups, I had forgetten to include one screenshot to give you the full range of results.
As previously said, if I instead select "OU" (OR) then nothing show up.
![Capture d’écran de 2021-11-07 13-45-04](https://user-images.githubusercontent.com/5779633/140657783-b9d33785-1c09-46df-85f1-d464288f1e08.png)

**Comment by smilerz** [comment] 2021-11-07 19:38
That’s because you don’t have any recipes that have pork and poultry.

**Comment by jpbaril** [comment] 2021-11-07 20:22
I know, I just wanted to include the full picture.
As you said, "Right now having the toggle on "OR" only does search on the selected keyword or food - ignoring children."
I maybe did not explain well in the ticket description, but that's what I would like that the search does: include children keywords.

**Closed** 2022-01-13 16:22 UTC
Labels: enhancement
