### ISSUE TITLE
Option to disabel Username and Password Auth

### ISSUE THREAD

**Issue by markussiebert** [TandoorRecipes/recipes#2851] opened 2024-01-02 15:15 UTC
### Is your feature request related to a problem? Please describe.

Hi, as I successfully configured social auth with Tandoor, I would like to disable the username/password auth.  

### Describe the solution you'd like

It would be great if there would be a simple flag via environment variable that disables the login prompt.

### Describe alternatives you've considered

no

**Comment by Kaaybi** [comment] 2024-02-11 13:55
Sounds like it's a duplicate of #2359

**Closed** 2024-02-12 16:12 UTC
Labels: enhancement
