### ISSUE TITLE
Translation tool: Let's encrypt certificate revoked

### ISSUE THREAD

**Issue by zcei** [TandoorRecipes/recipes#1438] opened 2022-01-30 01:21 UTC
### Tandoor Version

n/a

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Bug description

Hej there,

I was just trying out Tandoor for the very first time and like it a lot. Stumbled across some missing bits of translations and wanted to head over to the translation tool to get started on contributing.

The self-hosted weblate instance at https://translate.tandoor.dev/ uses an invalid certificate according to my machine.

![image](https://user-images.githubusercontent.com/1705507/151682910-fc834f03-2f9f-4d2b-9f55-57c5f1dd87e9.png)

I wonder whether this is intentional (moving things around right now?) or due to a misconfigured Let's encrypt setup?

Sorry, sadly no way for me to help out with a PR here as it's solely about your infrastructure's configuration. Would have hoped for my first issue to be more helpful. 😅 

### Relevant logs

```shell
macOS 12.1 (21C52)
Chrome Version 97.0.4692.99 (Official Build) (x86_64)
```

**Comment by MaxJa4** [comment] 2022-01-30 13:02
I'm having certificate issues like that too.

Info: https://www.bleepingcomputer.com/news/security/lets-encrypt-is-revoking-lots-of-ssl-certificates-in-two-days/

Seems like a global issue.

**Comment by MaxJa4** [comment] 2022-01-30 13:42
The host needs to renew the certificates, then it will work flawlessly again (just did that with my services).

In the meantime, if your browser lets you, you can choose to ignore that warning and access the site anyway.

**Comment by vabene1111** [comment] 2022-01-31 10:40
is this issue still present for you because for me its gone and i did not change anything ?

i suspect that certbot just automatically renewed the cert but its valid from 10.12.2021 so i am not sure if its just not showing for me because i was already on the site before.

**Comment by MaxJa4** [comment] 2022-01-31 11:01
Yes the issue is still present. 

Maybe try to access it in incognito mode with your browser and delete cache, maybe that helps to see the current status.

**Comment by vabene1111** [comment] 2022-01-31 11:32
very interesting, even incognito worked in chrome but when using tor i got the error. 

I deleted the old cert and got a new one, now its working both in chrome and tor for me. Closing this feel free to comment if it works for you as well or not.

also thanks for contributing to the translations :)

**Closed by vabene1111** 2022-01-31 11:32 UTC

**Comment by MaxJa4** [comment] 2022-01-31 12:11
Works again! :)
