### ISSUE TITLE
Display errors on recipe context menu in meal planner

### ISSUE THREAD

**Issue by philip-n** [TandoorRecipes/recipes#1418] opened 2022-01-26 15:58 UTC
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

**A** When opening the meal planner and clicking on the three dots menu of any recipe, the context menu initially appears in the bottom-left corner of the window. Subsequent clicks show it at the correct location.

**B** The context menu never disappears. Both after clicking somewhere else on screen and after activating one of the context menu items the context menu is still visible.

*Tested in chromium 97.0.4692.99 and firefox 96.0. See browser logs for both errors below.*

### Relevant logs

```shell
Case A (menu shown in lower corner):

TypeError: t is undefined
    oe https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:1046
    e https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:1046
    e https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:1046
    open https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    openContextMenu https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    n https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $emit https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    click https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    n https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    _wrapper https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Uo https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    No https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    w https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Fi https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    _update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    r https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    get https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    or https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    In https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $mount https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $mount https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    init https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    h https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    O https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    B https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    L https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    B https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    L https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    B https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    L https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    B https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    L https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Fi https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    _update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    r https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    get https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    run https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Zn https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    gt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    At https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    promise callback*ct https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    gt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    rr https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    notify https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    set https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    set https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    periodChangedCallback https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    promise callback*periodChangedCallback https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    handler https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:544
    ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $watch https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    vr https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    br https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    cr https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    _init https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    a https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    un https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    init https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    h https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    v https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Fi https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    _update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    r https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    get https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    or https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    In https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $mount https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $mount https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    init https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    h https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
chunk-vendors.d286c480be2e.js:503:12167

----------------------------------------------------------------------------------

Case B (menu not disappearing):

TypeError: r is null
    fn https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    r https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Qt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    r https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    _render https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    r https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    get https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    run https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Zn https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    gt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    At https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    promise callback*ct https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    gt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    rr https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    notify https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    set https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    set https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    close https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    a https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:1011
    bind https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:1011
    Yi https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Ui https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Ii https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    w https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    f https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Fi https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    _update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    r https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    get https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    run https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    Zn https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    gt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    At https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    promise callback*ct https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    gt https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    rr https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    update https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    notify https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    set https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    set https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    open https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    openContextMenu https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
    ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    n https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    ot https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    $emit https://MY_URL.XYZ/static/vue/js/chunk-vendors.d286c480be2e.js:503
    click https://MY_URL.XYZ/static/vue/js/meal_plan_view.abec696ac10d.js:1
chunk-vendors.d286c480be2e.js:503:12167
```

**Comment by vabene1111** [comment] 2022-01-26 16:23
thanks for reporting :)

**Comment by Kaibu** [comment] 2022-02-23 22:19
Weird, I've seen this happen somewhere but can't reproduce it rn

**Comment by vabene1111** [comment] 2022-02-27 10:35
no longer reproducable, maybe dependency update fixed this. Closing for now check again in next version

**Closed by vabene1111** 2022-02-27 10:35 UTC
Labels: bug, frontend
