### ISSUE TITLE
"NaN" in ingrediant list

### ISSUE THREAD

**Issue by Torsten-** [TandoorRecipes/recipes#1463] opened 2022-02-01 13:55 UTC
Hi,

I'v just set up a new installation with docker compose.
After adding a recipe (manual) and adding ingrediants I just get "NaN":

![grafik](https://user-images.githubusercontent.com/1141290/151981147-1dcdc0fc-676a-4f6c-85d3-489b4e7f5234.png)

If I edit the recipe the ingrediants are all correct:

![grafik](https://user-images.githubusercontent.com/1141290/151981093-882c2449-bfdc-4b83-83b3-b9078533a8f1.png)

I've also imported recipes from chefkoch.de - there everything is fine.

**Comment by vabene1111** [comment] 2022-02-03 13:21
can you export that recipe and post it here so that i can test if i can reproduce the issue ?

**Comment by Torsten-** [comment] 2022-02-03 13:56
Sure, here it is.
[export.zip](https://github.com/TandoorRecipes/recipes/files/7995099/export.zip)

**Comment by vabene1111** [comment] 2022-02-04 15:52
thanks for your recipe. The problem is actually that your recipe has 0 servings. This of course should not be possible but i have pushed a fix so its gone fore the next version. What you can easily do to fix your problem is just set the servings to "1" or similar. 

thanks for reporting and providing the export for quick debugging

**Closed by vabene1111** 2022-02-04 15:52 UTC
Labels: question

**Comment by smilerz** [comment] 2022-02-04 15:55
you can also 'Disable Amount' via the ingredient context menu

**Comment by Torsten-** [comment] 2022-02-05 09:05
Thanks for the quick fix.
I found the problem: I did type in an amount. I typed in 0,4 as amount servings an "L" as text (so 0,4 liter). But it seems that the amount needs to be an integer and can't be a float? 
I've just tested with the newest "latest" docker container right now, neither 0,4 nor 0.4 does work - it gets reset to 0 ervery time.

I'll just set it to 1, but maybe this is another little bit to fix ;-)

**Comment by vabene1111** [comment] 2022-02-05 10:15
yea i screwed that up, i implemented a "quick fix" that simply checks for servings to be a proper float and if its not it sets it to 0 (which is stupid). It now sets it to 1 and if its 0 it sets it to 1 as well.

**Comment by Torsten-** [comment] 2022-02-05 10:16
ok, but should it gernerally be possible to enter decimal values / floats or is this filed meant to be just an integer?

**Comment by vabene1111** [comment] 2022-02-05 10:20
i think you should be able to enter floats. i have never done so i must admit .. but maybe the model is also an integer, would need to look that up but on the move right now
