### ISSUE TITLE
Idea: Reference table for unit conversion

### ISSUE THREAD

**Issue by 0utl4w** [TandoorRecipes/recipes#495] opened 2021-03-18 09:49 UTC
**Is your feature request related to a problem? Please describe.**
Not really related to a problem. When importing or creating recipes you often have different units for the same ingredient. 
For example for salt you can have g, cup, tea spoon, spoon, Prise and so on. If you select 2 recipes for the shopping list, and each recipe uses different units you see the ingredient 2 times on the shopping list (for example 3 tea spoons salt and, 5 g salt).

**Describe the solution you'd like**
An optional reference table where you can configure unit conversions per ingredient into SI-units (e.g. g or ml).

Example:

Ingredient      Unit 1         value 1    target unit    target value
salt                 tea spoon   1              g                   5
salt                 cup             1              g                   150
and so on

On the shopping list I would prefer to only see the ingredients in SI-units (g). Maybe you can make the standard target unit per ingredient configurable.

If for one unit no conversion is configured you keep the actual behaviour.

**Describe alternatives you've considered**
Consider the target unit on each recipe already during creation of it.

**Comment by vabene1111** [comment] 2021-03-18 10:06
yes something like this is definitely planned. 

I was thinking of having a conversion table and a "prefered unit" per food.

**Comment by 0utl4w** [comment] 2021-03-18 10:16
Awesome, I'm excited!

**Comment by jpbaril** [comment] 2021-11-05 03:59
There should also have not only conversion between system of units, but there should also be equivalence/synonym/abbreviation mechanic for units.
Eg. 200 milliliters and 200 mL are the same thing. Same as 0,2 L and 200 mL.

Also, I think a base unit table should already be there by default to avoid misspelling.
Eg. It's mL, not ml.

**Comment by vabene1111** [comment] 2021-11-05 13:29
Base units are tricky since every country has their own systems but maybe we could have some. Apart from that the new automation feature aims to bring automatic conversion of different kinds of spelling variants so everything is always nicely standardized.

**Comment by smilerz** [comment] 2021-12-14 12:53
duplicate of #345

**Closed by smilerz** 2021-12-14 12:53 UTC
Labels: enhancement
